Global:
  debug: false
  use_gpu: false
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/output/recognizer_training
  save_epoch_step: 5
  eval_batch_step:
  - 0
  - 20
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/models/recognizer/character_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: false
  save_res_path: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/results/recognizer/predictions.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride:
    - 1
    - 2
    last_pool_type: avg
    last_pool_kernel_size:
    - 2
    - 2
  Head:
    name: MultiHead
    head_list:
    - CTCHead:
        Neck:
          name: svtr
          dims: 64
          depth: 2
          hidden_dims: 120
          use_guide: true
        Head:
          fc_decay: 1.0e-05
    - SARHead:
        enc_dim: 512
        max_text_length: 25
    character_dict_path: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/models/recognizer/character_dict.txt
Loss:
  name: MultiLoss
  loss_config_list:
  - CTCLoss: null
  - SARLoss: null
PostProcess:
  name: CTCLabelDecode
  character_dict_path: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/models/recognizer/character_dict.txt
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/data/recognizer/train
    ext_op_transform_idx: 1
    label_file_list:
    - D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/data/recognizer/train/rec_gt.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 25
    - RecAug: null
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: false
    num_workers: 0
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/data/recognizer/validation
    label_file_list:
    - D:/Actual Project/Indali_Lcd-Data-Extractor/packages/model-2-expanded-ppocr/data/recognizer/validation/rec_gt.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 16
    num_workers: 0
